### ISSUE TITLE
Create navigation route

### ISSUE THREAD

**Issue by SeokgyuYun** [Team-B1ND/dodamdodam-android#10]
## Overview (Required)

- Create `NavigationHost` in `MainActivity`

## Todo

- [x] Add compose navigation dependency
- [x] Create navigation graph
- [x] Add hilt dependency
