### ISSUE TITLE
[Setting, Wake up song] Add deactivation text / Fix my wake up song design

### ISSUE THREAD

**Issue by wsi1212** [Team-B1ND/dodamdodam-android#103]
## Overview (Required)

- Add deactivation text button in setting screen and fix my wake up song design

## Todo

- [x] Add deactivation text button
- [x] Add deactivation business logic
- [x] Fix my wake up song design

## ETC
- Fix my wake up song dialog padding
- Fix info screen name, email text field focus bug
- Fix Auth screen id, pw text field focus bug
