### ISSUE TITLE
[WakeUpSong] Fix wake up song bugs

### ISSUE THREAD

**Issue by wsi1212** [Team-B1ND/dodamdodam-android#106]
## Overview (Required)

-  Fix wake up song bugs

## Todo

- [x] Add padding between today title and list
- [x] Add padding in ask wake up song title and list
- [x] Get panding wake up song list after delete my wake up song
- [x] Add padding in wake up song card
