### ISSUE TITLE
Release 도담도담 v3.0.0

### ISSUE THREAD

**Issue by SeokgyuYun** [Team-B1ND/dodamdodam-android#109]
## Overview (Required)

- Release 도담도담 to Google Play Store

## Todo

- [x] update version to 3.0.0
- [x] update version code to 1
- [x] update base url to https://dodamapi.b1nd.com/
