### ISSUE TITLE
Setting to MainActivity Koin module

### ISSUE THREAD

**Issue by 8954sood** [Team-B1ND/dodamdodam-android#126]
## Overview (Required)

- Set up the coin environment for the main activity.

## Todo

- [x] Add dependencies Koin
- [x] Add Koin build logic plugin
- [x] Add MainActivity Koin Module Setting
