### ISSUE TITLE
Create KMP Network Modules

### ISSUE THREAD

**Issue by 8954sood** [Team-B1ND/dodamdodam-android#154]
## Overview (Required)

- For the Compose MultiPlatform Dodam Teacher, all core modules must be converted to KMP modules.

## Todo

- [ ] Migration to Android Native Module to KMP Module
- [ ] Create KMP Plugin
- [ ] Set Ktor iOS/Android Client
