### ISSUE TITLE
Create Dodam Teacher Android/iOS Module

### ISSUE THREAD

**Issue by 8954sood** [Team-B1ND/dodamdodam-android#158]
## Overview (Required)

- In fact, you need to set up a module that turns on the app to test and distribute various modules.

## Todo

- [x] Run iOS Simulator
- [x] Run Android Simulator
- [x] Set Dodam Teacher Module
