### ISSUE TITLE
Create Teahcer NightStudy Feature

### ISSUE THREAD

**Issue by wnsgur1** [Team-B1ND/dodamdodam-android#171]
## Overview (Required)

- Create NightStudy Screen
- Create NightStudy Feature
- Create NightStudy Navigation
- Create User Item

## Todo

- [x] Create NightStudy Screen
- [ ] Create NightStudy Feature
- [x] Create NightStudy Navigation
- [x] Create User Item
