### ISSUE TITLE
Create Approve Night Study

### ISSUE THREAD

**Issue by wnsgur1** [Team-B1ND/dodamdodam-android#190]
## Overview (Required)

- Approve Night Study Screen
- Approve Night Study Feature
- Approve Night Study Navigation
- Navigate Home To Approve Screen
- Move the screen according to the title

## Todo

- [x] Approve Night Study Screen
- [x] Approve Night Study Feature
- [x] Approve Night Study Navigation
- [x]  Navigate Home To Approve Screen
- [x] Move the screen according to the title
