### ISSUE TITLE
[Designsystem] Create bottom navigation component

### ISSUE THREAD

**Issue by SeokgyuYun** [Team-B1ND/dodamdodam-android#21]
## Overview (Required)

- Create bottom navigation component

## Todo

- [x] Add icons for bottom navigation
- [x] Create bottom navigation component
- [x] Add animation to bottom navigation
