### ISSUE TITLE
Set Meal Date Today

### ISSUE THREAD

**Issue by wnsgur1** [Team-B1ND/dodamdodam-android#216]
## Overview (Required)

- Set Meal Date Today
- Add Padding To All Card Item
- Edit Approve Outing Minute

## Todo

- [x] Set Meal Date Today
- [x] Add Padding To All Card Item
- [x] Edit Approve Outing Minute
