### ISSUE TITLE
Create Core Notice View

### ISSUE THREAD

**Issue by 8954sood** [Team-B1ND/dodamdodam-android#266]
## Overview (Required)

- Create Notice View

## Todo

- [ ] Create Notice View
- [ ] Change Bottom Nav Item
- [ ] Home Meal Card navigate to meal screen on touch
