### ISSUE TITLE
[Database] Create database module

### ISSUE THREAD

**Issue by SeokgyuYun** [Team-B1ND/dodamdodam-android#36]
## Overview (Required)

- Create and set up `SQLDelight` database

## Todo

- [x] Add SQLDelight dependencies
- [x] Create SQLDelight database object
- [x] Create hilt module that inject database object
