### ISSUE TITLE
[All] Create all screen

### ISSUE THREAD

**Issue by wsi1212** [Team-B1ND/dodamdodam-android#64]
## Overview (Required)

- Create all screen

## Todo

- [x] Create all screen view
- [x] Create get my info logic
- [x] Set navigation on main screen
