### ISSUE TITLE
[Bus] Create bus screen

### ISSUE THREAD

**Issue by wsi1212** [Team-B1ND/dodamdodam-android#74]
## Overview (Required)

- Create bus screen

## Todo

- [ ] Create bus loading screen
- [ ] Create determine current bus logic
- [ ] Create bus screen
- [ ] Create bus business logic
