### ISSUE TITLE
Add padding outing, nightstudy page and Remove default splish

### ISSUE THREAD

**Issue by wsi1212** [Team-B1ND/dodamdodam-android#89]
## Overview (Required)

- Add padding out, nightstudy pages and Remove android default splish

## Todo

- [x] Add padding outing page
- [x] Add padding nightstudy page
- [x] Add reject reason
- [x] Remove android default splish
